### ISSUE TITLE
the project will be further developed

### ISSUE THREAD

**Issue by jus61** [TMNFr33d0m/A3M-PMC-Simulator#10]
the project will be further developed?

**Comment by TMNFr33d0m** [comment]
Yes, but as a total modification!! Release by 10/31/15! This GH branch, however, is the mission file. At this time, the production of the mission file has been terminated. 

Please See: https://forums.bistudio.com/topic/184069-mpco-42-a3m-pmc-simulator/

**Comment by jus61** [comment]
Thanks for the info, it can hardly expect
