### ISSUE TITLE
Missing Some ; and ACE3 Medic

### ISSUE THREAD

**Issue by avka90** [TMNFr33d0m/A3M-PMC-Simulator#2]
File dialogs\FleetMgmt.hpp, line 39: '/A3M_store/Controls/A3M_Exitbutton.action': Missing ';' at the end of line
File dialogs\AdminPanel.hpp, line 32: '/A3M_AdminPanel/Controls/A3M_ExitButton.action': Missing ';' prior '}'
File dialogs\AdminPanel.hpp, line 43: '/A3M_AdminPanel/Controls/A3M_10k2All.action': Missing ';' prior '}'
File dialogs\AdminPanel.hpp, line 55: '/A3M_AdminPanel/Controls/A3M_CancelAllMissions.action': Missing ';' prior '}'
File dialogs\2ABCT_M4R.hpp, line 69: '/DRI_2ABCT_M4R/Controls/M4R_LaneA_Button2.action': Missing ';' prior '}'
File description.ext, line 22: '.wreckRemovalMaxTime': Missing ';' at the end of line

Using the newest ACE3 is not working with your mission. You are using the Medic Modul ACE_moduleMedicalSettings. 

In the newest ACE3 this Modul doesnt exist anymore. There is a new one named ACE_moduleTreatmentSettings. And i cant get it working with it. 

The ACE3 version linked in your Armaholic Post should be fine it starts at least but didnt testet it.

The Armaholic Version of your mission is missing 2 jpegs.
Warning Message: Picture images\flag1.jpg not found
Warning Message: Picture images\loadimg.jpg not found

sorry for bad english i hope you can understand whats wrong :D

**Comment by TMNFr33d0m** [comment]
Did you mix up ACE_moduleMedicalSettings with ACE_moduleTreatmentSettings by any chance? According to what I see, ACE_moduleTreatmentSettings is the old module. This version should be compatible with 3.0.0.3 and running ACE_moduleMedicalSettings. If you didnt mix them up, are you using a dev build by any chance?

**Comment by avka90** [comment]
Its possible that it was the dev build got the ACE3 version from github but with "your" version of ACE3 that is linked under the Armaholic Link it works fine

**Comment by TMNFr33d0m** [comment]
Pasted from STEAM for tracking purposes:

<quote> 

Again the Checkpoint Mission. It was a Event where a Truck stoped ~100m away from the checkpoint 1 guy dismounted and runned passed the checkpoint. when he was at the same hight as the checkpoint but ~30m away from it in the desert i arrested him and talked to him. got a message that the tension got easier. so far so got but the priest diditn go away after i relased him and i was stuck again
avka: so i went to the HQ and canceled all missions. all missions where canceled but when i try to get a new checkpoint mission i get. "there is already a checkpoint running" ore something like that.
</quote>

**Comment by TMNFr33d0m** [comment]
No mantype was found. Phantom Exec
^^ You know what this is, add sleeps between personality randomization and use spawn not call.

**Comment by avka90** [comment]
CO1 setSimpleTaskDestination (getPos Laptop1);
CO1 setTaskState "Created";
pl>
 Error position: <Laptop1);
CO1 setTaskState "Created";
pl>
Error Undefined variable in expression: laptop1
File mpmissions\co@x_a3m-pmc-simulator_Updated.Altis\scripts\initask1.sqf, line 42

typo in the mission.sqm  laptop1 != Laptop1

**Comment by avka90** [comment]
No mantype was found. Phantom Exec
^^ You know what this is, add sleeps between personality randomization and use spawn not call.

where to fix this tried it but it is not working ;)

**Comment by TMNFr33d0m** [comment]
Sorry. that wasn't directed at you, it was more of a note to self :-)
