### ISSUE TITLE
Vanilla version of the mission

### ISSUE THREAD

**Issue by SGTGunner** [TMNFr33d0m/A3M-PMC-Simulator#5]
Has there been any consideration around using just the vanilla version of ARMA 3? 
Instead of the current dependencies, which are the following:
- ALiVE (Req)
- ACE 3 (Req)
- Leights OPFOR Pack (Req)

I see that you could have a vanilla version (script only) and an enhanced version (with mods). After all, depending on what features you are leveraging you could do a lot of it in script.

PM me on steam @ SGTGunner and let me know if you are interested as I can help out.

Thanks.

**Comment by TMNFr33d0m** [comment]
There is a mod-free version, it typically lags behind the modded version, as the modded version is the one I personally prefer :-P https://github.com/TMNFr33d0m/A3M-PMC-Simulator/tree/TMN_Revive
is the "TMN Revive" branch. Requires no mods! I'll update it to the newest version tonight, as it's been on my self-nagging list for a week now.
