### ISSUE TITLE
Add Headless Client Supports

### ISSUE THREAD

**Issue by TandelK** [TMNFr33d0m/A3M-PMC-Simulator#6]
I already tried to add the Headless Clients to this mission and its working good. Here is the video details and i have already edited and added to my version. I check all the AI load on ASM seems to be on Remote. 

Make sure to add this one as it works fine with ALiVE 

https://www.youtube.com/watch?v=N64ewXDg0zk

**Comment by TMNFr33d0m** [comment]
Nice!! Believe it or not, long ago, this mission used to support up to 4 HCs! I pulled the functionality out, however, as most people don't know how to use HC and found the feature unnecessary, and I found myself spending a LOT of time trying to teach people how to use it. I will definitely consider adding the HC Functionality back to the mission! Thanks for the suggestion.

**Comment by TandelK** [comment]
Good. If you want i can help you with making the video on youtube and you can show them directly how to use Headless Client. ?
