### ISSUE TITLE
remove revive system and sit script for ace3

### ISSUE THREAD

**Issue by xBloodshed** [TMNFr33d0m/A3M-PMC-Simulator#8]
How/what to remove the a3m revive and sit script, cause ace3 already has the same

**Comment by TMNFr33d0m** [comment]
A3M Revive can be toggled on / off via the mission parameters. Sit script is an addAction in every chair, pain in the ass to remove, but simply load files from A3M_Revive version into your editor, find each chair and revoke the sitdown action. 

FYI, the modded version doesn't have A3M Revive, and already has ACE 3 support :-)
